--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchantsShop
branches:
  - master
projects:
  PiggyCustomEnchantsShop:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: CortexPE/Commando/Commando
        version: ^0.5
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^1.0.1
    lint:
      phpstan: false
...