name: PiggyCustomEnchantsShop
main: DaPigGuy\PiggyCustomEnchantsShop\PiggyCustomEnchantsShop
version: 1.3.1
api: 3.2.0
load: POSTWORLD
author: DaPigGuy
depend: ["PiggyCustomEnchants"]
softdepend: ["EconomyAPI"]
permissions:
  piggycustomenchantsshop:
    default: op
    description: "Use everything in PiggyCustomEnchantsShop"
    children:
      piggycustomenchantsshop.sign:
        description: "Use all sign related permissions"
        default: op
        children:
          piggycustomenchantsshop.sign.break:
            default: op
            descriptiom: "Break CE shop signs"
          piggycustomenchantsshop.sign.create:
            default: op
            description: "Create CE shop signs"
          piggycustomenchantsshop.sign.use:
            default: true
            description: "Use CE shop signs"
      piggycustomenchantsshop.command:
        default: op
        description: "Use all PiggyCustomEnchantsShop commands"
        children:
          piggycustomenchantsshop.command.ceshop:
            default: op
            description: "Use /ceshop"
            children:
              piggycustomenchantsshop.command.ceshop.add:
                default: op
                description: "Use /ceshop add"
              piggycustomenchantsshop.command.ceshop.use:
                default: true
                description: "Use /ceshop"