name: PiggyCustomEnchantsShop
main: PiggyCustomEnchantsShop\Main
version: 1.1.0
api: 3.0.0
load: POSTWORLD
author: DaPigGuy
permissions:
  piggycustomenchantsshop:
    default: op
    description: "Use everything in PiggyCustomEnchantsShop"
    children:
      piggycustomenchantsshop.breaksign:
        default: op
        descriptiom: "Break CE shop signs"
      piggycustomenchantsshop.makesign:
        default: op
        description: "Make CE shop signs"
      piggycustomenchantsshop.usesign:
        default: true
        description: "Use CE shop signs"
      piggycustomenchantsshop.command:
        default: false
        description: "Use all PiggyCustomEnchantsShop commands"
        children:
          piggycustomenchantsshop.command.ceshop:
            default: false
            description: "Use /ceshop"
            children:
              piggycustomenchantsshop.command.ceshop.add:
                default: op
                description: "Use /ceshop add"
              piggycustomenchantsshop.command.ceshop.use:
                default: true
                description: "Use /ceshop"