economy:
  provider: bedrockeconomy
  currency-format: "${amount}"
enchant-limit: -1
shop-types:
  sign:
    enabled: true
    double-tap: true
    format:
      line-one: "[&aCE&r]"
      line-two: "{enchantment}"
      line-three: "Level: {level}"
      line-four: "Price: {price}"
  ui:
    enabled: true