# PiggyCustomEnchantsShop Configuration

# Whether to use SignShop or UIShop.
# Options: sign | ui
shop-type: sign

# If SignShop is enabled, require users to double click for purchase.
# Options: true | false
double-tap: true
