economy:
  provider: EconomyS
  currency-format: "${amount}"
shop-types:
  sign:
    enabled: true
    double-tap: true
    format:
      line-one: "[&aCE&r]"
      line-two: "{enchantment}"
      line-three: "Level: {level}"
      line-four: "Price: {price}"
  ui:
    enabled: true